# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298b5cd633cb3556b97ec571f8697198ed4091ef4eddaa2ead4fea1bcb9acd33bc5e1773a5808479d782ff0913cb8ee32772edfc5fc8f403aee165c048c5c19d

test:
  secret_key_base: e68d7c48199527152d43cef55ac5f087e6f6b0152db43c4911633ce272d28cd5ee0a7d42c78370fd375caf8152b1a7af228775dd53549814badbb34f243d1131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
